### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by alome007** [hearsilent/AmazingAvatar#3]
After been expanded for the second time, the username disappears

**Comment by hearsilent** [comment]
@Alome007 Can you share screen record?

**Comment by abqamar** [comment]
I am facing the same issue. After expanding for second time, title disappears. 
(https://user-images.githubusercontent.com/34501690/67626658-6ca75d00-f85f-11e9-84c8-2b7f024b6dfd.gif)

**Comment by hearsilent** [comment]
@abqamar Can you provide example code?
