### ISSUE TITLE
title positon is wrong

### ISSUE THREAD

**Issue by byzyhm** [hearsilent/AmazingAvatar#6]
if the name is too long, name TextView's postion is wrong
`private void fetchAvatar() {
		NetworkHelper.getAvatar(new AvatarCallback() {

			@Override
			public void onSuccess(final AvatarModel avatarModel) {
				super.onSuccess(avatarModel);
				if (isFinishing()) {
					return;
				}
				runOnUiThread(new Runnable() {

					@Override
					public void run() {
						Glide.with(MainActivity.this).load(avatarModel.url).into(mAvatarImageView);
						String name = String.format(Locale.getDefault(), "%s %s", avatarModel.firstName, avatarModel.lastName);
						mTitleTextView.setText("namenamenamenamenamenamenamenamename" + name);
						mTitleTextView.post(new Runnable() {

							@Override
							public void run() {
								resetPoints(true);
							}
						});
					}
				});
			}
		});
	}`

**Comment by hearsilent** [comment]
Hi @OnThinIce, can you provide demo video?
In my case, it's work correct.

**Comment by byzyhm** [comment]
you can set a long name, like this:
in NetworkHelper.getAvatar method
mTitleTextView.setText("namenamenamenamenamenamenamenamename" + name);

**Comment by hearsilent** [comment]
Hi @OnThinIce,
I've tried, it's work correct.

**Comment by byzyhm** [comment]
sorry, i changed some code, now i can't recurrent.....
ps: you can add a image after the name？scroll with the name...so hard...  o.0

**Comment by hearsilent** [comment]
Hi @OnThinIce,
You can use `android:drawableEnd`

**Comment by byzyhm** [comment]
> Hi @OnThinIce,
> You can use `android:drawableEnd`

this image need sliding scale，，，
